/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class CommandStatus {
  public final static CommandStatus StatusInProgress = new CommandStatus("StatusInProgress", neoradio2JNI.StatusInProgress_get());
  public final static CommandStatus StatusFinished = new CommandStatus("StatusFinished");
  public final static CommandStatus StatusError = new CommandStatus("StatusError");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CommandStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CommandStatus.class + " with value " + swigValue);
  }

  private CommandStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CommandStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CommandStatus(String swigName, CommandStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CommandStatus[] swigValues = { StatusInProgress, StatusFinished, StatusError };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

