/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface neoradio2Constants {
  public final static int NEORADIO2_SUCCESS = neoradio2JNI.NEORADIO2_SUCCESS_get();
  public final static int NEORADIO2_FAILURE = neoradio2JNI.NEORADIO2_FAILURE_get();
  public final static int NEORADIO2_ERR_WBLOCK = neoradio2JNI.NEORADIO2_ERR_WBLOCK_get();
  public final static int NEORADIO2_ERR_INPROGRESS = neoradio2JNI.NEORADIO2_ERR_INPROGRESS_get();
  public final static int NEORADIO2_ERR_FAILURE = neoradio2JNI.NEORADIO2_ERR_FAILURE_get();
  public final static int NEORADIO2_MAX_DEVS = neoradio2JNI.NEORADIO2_MAX_DEVS_get();
}
