/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Neoradio2DeviceInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Neoradio2DeviceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Neoradio2DeviceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        neoradio2JNI.delete_Neoradio2DeviceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    neoradio2JNI.Neoradio2DeviceInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return neoradio2JNI.Neoradio2DeviceInfo_name_get(swigCPtr, this);
  }

  public void setSerial_str(String value) {
    neoradio2JNI.Neoradio2DeviceInfo_serial_str_set(swigCPtr, this, value);
  }

  public String getSerial_str() {
    return neoradio2JNI.Neoradio2DeviceInfo_serial_str_get(swigCPtr, this);
  }

  public void setVendor_id(int value) {
    neoradio2JNI.Neoradio2DeviceInfo_vendor_id_set(swigCPtr, this, value);
  }

  public int getVendor_id() {
    return neoradio2JNI.Neoradio2DeviceInfo_vendor_id_get(swigCPtr, this);
  }

  public void setProduct_id(int value) {
    neoradio2JNI.Neoradio2DeviceInfo_product_id_set(swigCPtr, this, value);
  }

  public int getProduct_id() {
    return neoradio2JNI.Neoradio2DeviceInfo_product_id_get(swigCPtr, this);
  }

  public void set_reserved(SWIGTYPE_p_uint8_t value) {
    neoradio2JNI.Neoradio2DeviceInfo__reserved_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t get_reserved() {
    long cPtr = neoradio2JNI.Neoradio2DeviceInfo__reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public Neoradio2DeviceInfo() {
    this(neoradio2JNI.new_Neoradio2DeviceInfo(), true);
  }

}
