/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module neoradio2;

static import neoradio2_im;
static import tango.stdc.config;
static import tango.stdc.stringz;


enum CommandStatus {
  StatusInProgress = 0,
  StatusFinished,
  StatusError
}

enum CommandStateType {
  CommandStateHost = 0,
  CommandStateDevice,
  CommandStateUnknown = -1
}

int NEORADIO2_SUCCESS() {
  auto ret = neoradio2_im.NEORADIO2_SUCCESS_get();
  return ret;
}

int NEORADIO2_FAILURE() {
  auto ret = neoradio2_im.NEORADIO2_FAILURE_get();
  return ret;
}

int NEORADIO2_ERR_WBLOCK() {
  auto ret = neoradio2_im.NEORADIO2_ERR_WBLOCK_get();
  return ret;
}

int NEORADIO2_ERR_INPROGRESS() {
  auto ret = neoradio2_im.NEORADIO2_ERR_INPROGRESS_get();
  return ret;
}

int NEORADIO2_ERR_FAILURE() {
  auto ret = neoradio2_im.NEORADIO2_ERR_FAILURE_get();
  return ret;
}

int NEORADIO2_MAX_DEVS() {
  auto ret = neoradio2_im.NEORADIO2_MAX_DEVS_get();
  return ret;
}

class Neoradio2DeviceInfo {
  private void* swigCPtr;
  protected bool swigCMemOwn;

  public this(void* cObject, bool ownCObject) {
    swigCPtr = cObject;
    swigCMemOwn = ownCObject;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin neoradio2_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          neoradio2_im.delete_Neoradio2DeviceInfo(cast(void*)swigCPtr);
        }
        swigCPtr = null;
      }
    }
  }

  public void name(char[] value) {
    neoradio2_im.Neoradio2DeviceInfo_name_set(cast(void*)swigCPtr, (value ? tango.stdc.stringz.toStringz(value) : null));
  }

  public char[] name() {
    char[] ret = tango.stdc.stringz.fromStringz(neoradio2_im.Neoradio2DeviceInfo_name_get(cast(void*)swigCPtr));
    return ret;
  }

  public void serial_str(char[] value) {
    neoradio2_im.Neoradio2DeviceInfo_serial_str_set(cast(void*)swigCPtr, (value ? tango.stdc.stringz.toStringz(value) : null));
  }

  public char[] serial_str() {
    char[] ret = tango.stdc.stringz.fromStringz(neoradio2_im.Neoradio2DeviceInfo_serial_str_get(cast(void*)swigCPtr));
    return ret;
  }

  public void vendor_id(int value) {
    neoradio2_im.Neoradio2DeviceInfo_vendor_id_set(cast(void*)swigCPtr, value);
  }

  public int vendor_id() {
    auto ret = neoradio2_im.Neoradio2DeviceInfo_vendor_id_get(cast(void*)swigCPtr);
    return ret;
  }

  public void product_id(int value) {
    neoradio2_im.Neoradio2DeviceInfo_product_id_set(cast(void*)swigCPtr, value);
  }

  public int product_id() {
    auto ret = neoradio2_im.Neoradio2DeviceInfo_product_id_get(cast(void*)swigCPtr);
    return ret;
  }

  public void _reserved(SWIGTYPE_p_uint8_t value) {
    neoradio2_im.Neoradio2DeviceInfo__reserved_set(cast(void*)swigCPtr, SWIGTYPE_p_uint8_t.swigGetCPtr(value));
  }

  public SWIGTYPE_p_uint8_t _reserved() {
    void* cPtr = neoradio2_im.Neoradio2DeviceInfo__reserved_get(cast(void*)swigCPtr);
    SWIGTYPE_p_uint8_t ret = (cPtr is null) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
    return ret;
  }

  public this() {
    this(neoradio2_im.new_Neoradio2DeviceInfo(), true);
  }
}

enum StatusType {
  StatusChain = 0,
  StatusAppStart,
  StatusPCBSN,
  StatusSensorRead,
  StatusSensorWrite,
  StatusSettingsRead,
  StatusSettingsWrite,
  StatusCalibration,
  StatusCalibrationPoints,
  StatusCalibrationStored,
  StatusCalibrationInfo,
  StatusLedToggle,
  StatusMax
}

class SWIGTYPE_p_uint8_t {
  private void* swigCPtr;

  public this(void* cObject, bool futureUse) {
    swigCPtr = cObject;
  }

  protected this() {
    swigCPtr = null;
  }

  public static void* swigGetCPtr(typeof(this) obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin neoradio2_im.SwigOperatorDefinitions;
}
