/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: swig.i

package neoradio2

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef int intgo;
typedef unsigned int uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
extern void _wrap_Swig_free_neoradio2_6add94b58477e935(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_neoradio2_6add94b58477e935(swig_intgo arg1);
extern swig_intgo _wrap_StatusInProgress_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusFinished_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusError_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_CommandStateHost_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_CommandStateDevice_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_CommandStateUnknown_neoradio2_6add94b58477e935(void);
extern void _wrap_Neoradio2DeviceInfo_name_set_neoradio2_6add94b58477e935(uintptr_t arg1, swig_type_1 arg2);
extern swig_type_2 _wrap_Neoradio2DeviceInfo_name_get_neoradio2_6add94b58477e935(uintptr_t arg1);
extern void _wrap_Neoradio2DeviceInfo_serial_str_set_neoradio2_6add94b58477e935(uintptr_t arg1, swig_type_3 arg2);
extern swig_type_4 _wrap_Neoradio2DeviceInfo_serial_str_get_neoradio2_6add94b58477e935(uintptr_t arg1);
extern void _wrap_Neoradio2DeviceInfo_vendor_id_set_neoradio2_6add94b58477e935(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Neoradio2DeviceInfo_vendor_id_get_neoradio2_6add94b58477e935(uintptr_t arg1);
extern void _wrap_Neoradio2DeviceInfo_product_id_set_neoradio2_6add94b58477e935(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Neoradio2DeviceInfo_product_id_get_neoradio2_6add94b58477e935(uintptr_t arg1);
extern void _wrap_Neoradio2DeviceInfo__reserved_set_neoradio2_6add94b58477e935(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_Neoradio2DeviceInfo__reserved_get_neoradio2_6add94b58477e935(uintptr_t arg1);
extern uintptr_t _wrap_new_Neoradio2DeviceInfo_neoradio2_6add94b58477e935(void);
extern void _wrap_delete_Neoradio2DeviceInfo_neoradio2_6add94b58477e935(uintptr_t arg1);
extern swig_intgo _wrap_StatusChain_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusAppStart_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusPCBSN_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusSensorRead_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusSensorWrite_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusSettingsRead_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusSettingsWrite_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusCalibration_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusCalibrationPoints_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusCalibrationStored_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusCalibrationInfo_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusLedToggle_neoradio2_6add94b58477e935(void);
extern swig_intgo _wrap_StatusMax_neoradio2_6add94b58477e935(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_neoradio2_6add94b58477e935(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Enum_SS__CommandStatus int
func _swig_getStatusInProgress() (_swig_ret Enum_SS__CommandStatus) {
	var swig_r Enum_SS__CommandStatus
	swig_r = (Enum_SS__CommandStatus)(C._wrap_StatusInProgress_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusInProgress Enum_SS__CommandStatus = _swig_getStatusInProgress()
func _swig_getStatusFinished() (_swig_ret Enum_SS__CommandStatus) {
	var swig_r Enum_SS__CommandStatus
	swig_r = (Enum_SS__CommandStatus)(C._wrap_StatusFinished_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusFinished Enum_SS__CommandStatus = _swig_getStatusFinished()
func _swig_getStatusError() (_swig_ret Enum_SS__CommandStatus) {
	var swig_r Enum_SS__CommandStatus
	swig_r = (Enum_SS__CommandStatus)(C._wrap_StatusError_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusError Enum_SS__CommandStatus = _swig_getStatusError()
type Enum_SS__CommandStateType int
func _swig_getCommandStateHost() (_swig_ret Enum_SS__CommandStateType) {
	var swig_r Enum_SS__CommandStateType
	swig_r = (Enum_SS__CommandStateType)(C._wrap_CommandStateHost_neoradio2_6add94b58477e935())
	return swig_r
}

var CommandStateHost Enum_SS__CommandStateType = _swig_getCommandStateHost()
func _swig_getCommandStateDevice() (_swig_ret Enum_SS__CommandStateType) {
	var swig_r Enum_SS__CommandStateType
	swig_r = (Enum_SS__CommandStateType)(C._wrap_CommandStateDevice_neoradio2_6add94b58477e935())
	return swig_r
}

var CommandStateDevice Enum_SS__CommandStateType = _swig_getCommandStateDevice()
func _swig_getCommandStateUnknown() (_swig_ret Enum_SS__CommandStateType) {
	var swig_r Enum_SS__CommandStateType
	swig_r = (Enum_SS__CommandStateType)(C._wrap_CommandStateUnknown_neoradio2_6add94b58477e935())
	return swig_r
}

var CommandStateUnknown Enum_SS__CommandStateType = _swig_getCommandStateUnknown()
const NEORADIO2_SUCCESS int = 0
const NEORADIO2_FAILURE int = 1
const NEORADIO2_ERR_WBLOCK int = 2
const NEORADIO2_ERR_INPROGRESS int = 3
const NEORADIO2_ERR_FAILURE int = 4
const NEORADIO2_MAX_DEVS int = 8
type SwigcptrNeoradio2DeviceInfo uintptr

func (p SwigcptrNeoradio2DeviceInfo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrNeoradio2DeviceInfo) SwigIsNeoradio2DeviceInfo() {
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetName(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Neoradio2DeviceInfo_name_set_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Neoradio2DeviceInfo_name_get_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetSerial_str(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Neoradio2DeviceInfo_serial_str_set_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetSerial_str() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Neoradio2DeviceInfo_serial_str_get_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetVendor_id(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Neoradio2DeviceInfo_vendor_id_set_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetVendor_id() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Neoradio2DeviceInfo_vendor_id_get_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetProduct_id(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Neoradio2DeviceInfo_product_id_set_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetProduct_id() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Neoradio2DeviceInfo_product_id_get_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetX_reserved(arg2 Uint8_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Neoradio2DeviceInfo__reserved_set_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetX_reserved() (_swig_ret Uint8_t) {
	var swig_r Uint8_t
	_swig_i_0 := arg1
	swig_r = (Uint8_t)(SwigcptrUint8_t(C._wrap_Neoradio2DeviceInfo__reserved_get_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewNeoradio2DeviceInfo() (_swig_ret Neoradio2DeviceInfo) {
	var swig_r Neoradio2DeviceInfo
	swig_r = (Neoradio2DeviceInfo)(SwigcptrNeoradio2DeviceInfo(C._wrap_new_Neoradio2DeviceInfo_neoradio2_6add94b58477e935()))
	return swig_r
}

func DeleteNeoradio2DeviceInfo(arg1 Neoradio2DeviceInfo) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Neoradio2DeviceInfo_neoradio2_6add94b58477e935(C.uintptr_t(_swig_i_0))
}

type Neoradio2DeviceInfo interface {
	Swigcptr() uintptr
	SwigIsNeoradio2DeviceInfo()
	SetName(arg2 string)
	GetName() (_swig_ret string)
	SetSerial_str(arg2 string)
	GetSerial_str() (_swig_ret string)
	SetVendor_id(arg2 int)
	GetVendor_id() (_swig_ret int)
	SetProduct_id(arg2 int)
	GetProduct_id() (_swig_ret int)
	SetX_reserved(arg2 Uint8_t)
	GetX_reserved() (_swig_ret Uint8_t)
}

type Enum_SS__StatusType int
func _swig_getStatusChain() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusChain_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusChain Enum_SS__StatusType = _swig_getStatusChain()
func _swig_getStatusAppStart() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusAppStart_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusAppStart Enum_SS__StatusType = _swig_getStatusAppStart()
func _swig_getStatusPCBSN() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusPCBSN_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusPCBSN Enum_SS__StatusType = _swig_getStatusPCBSN()
func _swig_getStatusSensorRead() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusSensorRead_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusSensorRead Enum_SS__StatusType = _swig_getStatusSensorRead()
func _swig_getStatusSensorWrite() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusSensorWrite_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusSensorWrite Enum_SS__StatusType = _swig_getStatusSensorWrite()
func _swig_getStatusSettingsRead() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusSettingsRead_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusSettingsRead Enum_SS__StatusType = _swig_getStatusSettingsRead()
func _swig_getStatusSettingsWrite() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusSettingsWrite_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusSettingsWrite Enum_SS__StatusType = _swig_getStatusSettingsWrite()
func _swig_getStatusCalibration() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusCalibration_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusCalibration Enum_SS__StatusType = _swig_getStatusCalibration()
func _swig_getStatusCalibrationPoints() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusCalibrationPoints_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusCalibrationPoints Enum_SS__StatusType = _swig_getStatusCalibrationPoints()
func _swig_getStatusCalibrationStored() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusCalibrationStored_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusCalibrationStored Enum_SS__StatusType = _swig_getStatusCalibrationStored()
func _swig_getStatusCalibrationInfo() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusCalibrationInfo_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusCalibrationInfo Enum_SS__StatusType = _swig_getStatusCalibrationInfo()
func _swig_getStatusLedToggle() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusLedToggle_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusLedToggle Enum_SS__StatusType = _swig_getStatusLedToggle()
func _swig_getStatusMax() (_swig_ret Enum_SS__StatusType) {
	var swig_r Enum_SS__StatusType
	swig_r = (Enum_SS__StatusType)(C._wrap_StatusMax_neoradio2_6add94b58477e935())
	return swig_r
}

var StatusMax Enum_SS__StatusType = _swig_getStatusMax()

type SwigcptrUint8_t uintptr
type Uint8_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint8_t) Swigcptr() uintptr {
	return uintptr(p)
}

