/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ../../swig.i

package neoradio2

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

var _wrap_Swig_free_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_neoradio2_67b190837e1cf255 unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_neoradio2_67b190837e1cf255, _swig_p)
	return
}
type _CommandStatus int
var _wrap_StatusInProgress_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusInProgress() (_swig_ret _CommandStatus) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusInProgress_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusInProgress _CommandStatus = _swig_getStatusInProgress()
var _wrap_StatusFinished_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusFinished() (_swig_ret _CommandStatus) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusFinished_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusFinished _CommandStatus = _swig_getStatusFinished()
var _wrap_StatusError_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusError() (_swig_ret _CommandStatus) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusError_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusError _CommandStatus = _swig_getStatusError()
type _CommandStateType int
var _wrap_CommandStateHost_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getCommandStateHost() (_swig_ret _CommandStateType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_CommandStateHost_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var CommandStateHost _CommandStateType = _swig_getCommandStateHost()
var _wrap_CommandStateDevice_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getCommandStateDevice() (_swig_ret _CommandStateType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_CommandStateDevice_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var CommandStateDevice _CommandStateType = _swig_getCommandStateDevice()
var _wrap_CommandStateUnknown_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getCommandStateUnknown() (_swig_ret _CommandStateType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_CommandStateUnknown_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var CommandStateUnknown _CommandStateType = _swig_getCommandStateUnknown()
const NEORADIO2_SUCCESS int = 0
const NEORADIO2_FAILURE int = 1
const NEORADIO2_ERR_WBLOCK int = 2
const NEORADIO2_ERR_INPROGRESS int = 3
const NEORADIO2_ERR_FAILURE int = 4
const NEORADIO2_MAX_DEVS int = 8
type SwigcptrNeoradio2DeviceInfo uintptr

func (p SwigcptrNeoradio2DeviceInfo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrNeoradio2DeviceInfo) SwigIsNeoradio2DeviceInfo() {
}

var _wrap_Neoradio2DeviceInfo_name_set_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo_name_set(base SwigcptrNeoradio2DeviceInfo, _ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo_name_set_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetName(arg2 string) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	_swig_wrap_Neoradio2DeviceInfo_name_set(arg1, arg2)
}

var _wrap_Neoradio2DeviceInfo_name_get_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo_name_get(base SwigcptrNeoradio2DeviceInfo) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo_name_get_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetName() (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_Neoradio2DeviceInfo_name_get(arg1)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_Neoradio2DeviceInfo_serial_str_set_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo_serial_str_set(base SwigcptrNeoradio2DeviceInfo, _ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo_serial_str_set_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetSerial_str(arg2 string) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	_swig_wrap_Neoradio2DeviceInfo_serial_str_set(arg1, arg2)
}

var _wrap_Neoradio2DeviceInfo_serial_str_get_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo_serial_str_get(base SwigcptrNeoradio2DeviceInfo) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo_serial_str_get_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetSerial_str() (_swig_ret string) {
	var swig_r string
	swig_r = _swig_wrap_Neoradio2DeviceInfo_serial_str_get(arg1)
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var _wrap_Neoradio2DeviceInfo_vendor_id_set_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo_vendor_id_set(base SwigcptrNeoradio2DeviceInfo, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo_vendor_id_set_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetVendor_id(arg2 int) {
	_swig_wrap_Neoradio2DeviceInfo_vendor_id_set(arg1, arg2)
}

var _wrap_Neoradio2DeviceInfo_vendor_id_get_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo_vendor_id_get(base SwigcptrNeoradio2DeviceInfo) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo_vendor_id_get_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetVendor_id() (_swig_ret int) {
	return _swig_wrap_Neoradio2DeviceInfo_vendor_id_get(arg1)
}

var _wrap_Neoradio2DeviceInfo_product_id_set_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo_product_id_set(base SwigcptrNeoradio2DeviceInfo, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo_product_id_set_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetProduct_id(arg2 int) {
	_swig_wrap_Neoradio2DeviceInfo_product_id_set(arg1, arg2)
}

var _wrap_Neoradio2DeviceInfo_product_id_get_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo_product_id_get(base SwigcptrNeoradio2DeviceInfo) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo_product_id_get_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetProduct_id() (_swig_ret int) {
	return _swig_wrap_Neoradio2DeviceInfo_product_id_get(arg1)
}

var _wrap_Neoradio2DeviceInfo__reserved_set_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo__reserved_set(base SwigcptrNeoradio2DeviceInfo, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo__reserved_set_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) SetX_reserved(arg2 Uint8_t) {
	_swig_wrap_Neoradio2DeviceInfo__reserved_set(arg1, arg2.Swigcptr())
}

var _wrap_Neoradio2DeviceInfo__reserved_get_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_Neoradio2DeviceInfo__reserved_get(base SwigcptrNeoradio2DeviceInfo) (_ SwigcptrUint8_t) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Neoradio2DeviceInfo__reserved_get_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func (arg1 SwigcptrNeoradio2DeviceInfo) GetX_reserved() (_swig_ret Uint8_t) {
	return _swig_wrap_Neoradio2DeviceInfo__reserved_get(arg1)
}

var _wrap_new_Neoradio2DeviceInfo_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_new_Neoradio2DeviceInfo() (base SwigcptrNeoradio2DeviceInfo) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Neoradio2DeviceInfo_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func NewNeoradio2DeviceInfo() (_swig_ret Neoradio2DeviceInfo) {
	return _swig_wrap_new_Neoradio2DeviceInfo()
}

var _wrap_delete_Neoradio2DeviceInfo_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_wrap_delete_Neoradio2DeviceInfo(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Neoradio2DeviceInfo_neoradio2_67b190837e1cf255, _swig_p)
	return
}

func DeleteNeoradio2DeviceInfo(arg1 Neoradio2DeviceInfo) {
	_swig_wrap_delete_Neoradio2DeviceInfo(arg1.Swigcptr())
}

type Neoradio2DeviceInfo interface {
	Swigcptr() uintptr
	SwigIsNeoradio2DeviceInfo()
	SetName(arg2 string)
	GetName() (_swig_ret string)
	SetSerial_str(arg2 string)
	GetSerial_str() (_swig_ret string)
	SetVendor_id(arg2 int)
	GetVendor_id() (_swig_ret int)
	SetProduct_id(arg2 int)
	GetProduct_id() (_swig_ret int)
	SetX_reserved(arg2 Uint8_t)
	GetX_reserved() (_swig_ret Uint8_t)
}

type _StatusType int
var _wrap_StatusChain_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusChain() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusChain_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusChain _StatusType = _swig_getStatusChain()
var _wrap_StatusAppStart_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusAppStart() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusAppStart_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusAppStart _StatusType = _swig_getStatusAppStart()
var _wrap_StatusPCBSN_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusPCBSN() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusPCBSN_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusPCBSN _StatusType = _swig_getStatusPCBSN()
var _wrap_StatusSensorRead_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusSensorRead() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusSensorRead_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusSensorRead _StatusType = _swig_getStatusSensorRead()
var _wrap_StatusSensorWrite_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusSensorWrite() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusSensorWrite_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusSensorWrite _StatusType = _swig_getStatusSensorWrite()
var _wrap_StatusSettingsRead_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusSettingsRead() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusSettingsRead_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusSettingsRead _StatusType = _swig_getStatusSettingsRead()
var _wrap_StatusSettingsWrite_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusSettingsWrite() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusSettingsWrite_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusSettingsWrite _StatusType = _swig_getStatusSettingsWrite()
var _wrap_StatusCalibration_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusCalibration() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusCalibration_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusCalibration _StatusType = _swig_getStatusCalibration()
var _wrap_StatusCalibrationPoints_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusCalibrationPoints() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusCalibrationPoints_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusCalibrationPoints _StatusType = _swig_getStatusCalibrationPoints()
var _wrap_StatusCalibrationStored_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusCalibrationStored() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusCalibrationStored_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusCalibrationStored _StatusType = _swig_getStatusCalibrationStored()
var _wrap_StatusCalibrationInfo_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusCalibrationInfo() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusCalibrationInfo_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusCalibrationInfo _StatusType = _swig_getStatusCalibrationInfo()
var _wrap_StatusLedToggle_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusLedToggle() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusLedToggle_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusLedToggle _StatusType = _swig_getStatusLedToggle()
var _wrap_StatusMax_neoradio2_67b190837e1cf255 unsafe.Pointer

func _swig_getStatusMax() (_swig_ret _StatusType) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StatusMax_neoradio2_67b190837e1cf255, _swig_p)
	return
}
var StatusMax _StatusType = _swig_getStatusMax()

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint8_t uintptr
type Uint8_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint8_t) Swigcptr() uintptr {
	return uintptr(p)
}

