//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Neoradio2DeviceInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Neoradio2DeviceInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Neoradio2DeviceInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Neoradio2DeviceInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          neoradio2PINVOKE.delete_Neoradio2DeviceInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string name {
    set {
      neoradio2PINVOKE.Neoradio2DeviceInfo_name_set(swigCPtr, value);
    } 
    get {
      string ret = neoradio2PINVOKE.Neoradio2DeviceInfo_name_get(swigCPtr);
      return ret;
    } 
  }

  public string serial_str {
    set {
      neoradio2PINVOKE.Neoradio2DeviceInfo_serial_str_set(swigCPtr, value);
    } 
    get {
      string ret = neoradio2PINVOKE.Neoradio2DeviceInfo_serial_str_get(swigCPtr);
      return ret;
    } 
  }

  public int vendor_id {
    set {
      neoradio2PINVOKE.Neoradio2DeviceInfo_vendor_id_set(swigCPtr, value);
    } 
    get {
      int ret = neoradio2PINVOKE.Neoradio2DeviceInfo_vendor_id_get(swigCPtr);
      return ret;
    } 
  }

  public int product_id {
    set {
      neoradio2PINVOKE.Neoradio2DeviceInfo_product_id_set(swigCPtr, value);
    } 
    get {
      int ret = neoradio2PINVOKE.Neoradio2DeviceInfo_product_id_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint8_t _reserved {
    set {
      neoradio2PINVOKE.Neoradio2DeviceInfo__reserved_set(swigCPtr, SWIGTYPE_p_uint8_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = neoradio2PINVOKE.Neoradio2DeviceInfo__reserved_get(swigCPtr);
      SWIGTYPE_p_uint8_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
      return ret;
    } 
  }

  public Neoradio2DeviceInfo() : this(neoradio2PINVOKE.new_Neoradio2DeviceInfo(), true) {
  }

}
