//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class neoradio2 {
  public static readonly int NEORADIO2_SUCCESS = neoradio2PINVOKE.NEORADIO2_SUCCESS_get();
  public static readonly int NEORADIO2_FAILURE = neoradio2PINVOKE.NEORADIO2_FAILURE_get();
  public static readonly int NEORADIO2_ERR_WBLOCK = neoradio2PINVOKE.NEORADIO2_ERR_WBLOCK_get();
  public static readonly int NEORADIO2_ERR_INPROGRESS = neoradio2PINVOKE.NEORADIO2_ERR_INPROGRESS_get();
  public static readonly int NEORADIO2_ERR_FAILURE = neoradio2PINVOKE.NEORADIO2_ERR_FAILURE_get();
  public static readonly int NEORADIO2_MAX_DEVS = neoradio2PINVOKE.NEORADIO2_MAX_DEVS_get();
}
