//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum StatusType {
  StatusChain = 0,
  StatusAppStart,
  StatusPCBSN,
  StatusSensorRead,
  StatusSensorWrite,
  StatusSettingsRead,
  StatusSettingsWrite,
  StatusCalibration,
  StatusCalibrationPoints,
  StatusCalibrationStored,
  StatusCalibrationInfo,
  StatusLedToggle,
  StatusMax
}
