# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -c++ -r -outcurrentdir ../../swig.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  assign(defName,  .values,  envir = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################



setClass('C++Reference', contains = 'ExternalReference')
setClass('_p__Neoradio2DeviceInfo', contains = 'ExternalReference')
setClass("_Neoradio2DeviceInfo",
    representation(
        name = "character",
        serial_str = "character",
        vendor_id = "integer",
        product_id = "integer"),
        contains = "RSWIGStruct")


# End class _Neoradio2DeviceInfo




setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

defineEnumeration('__CommandStatus',
                    .values = c(
                        'StatusInProgress' = 0, 
                        'StatusFinished' = 1, 
                        'StatusError' = 2
))
defineEnumeration('__CommandStateType',
                    .values = c(
                        'CommandStateHost' = 0, 
                        'CommandStateDevice' = 1, 
                        'CommandStateUnknown' = -1
))
# Start of Neoradio2DeviceInfo_name_set

`Neoradio2DeviceInfo_name_set` = function(self, s_name)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  
  if(is.list(s_name))
  assert(all(sapply(s_name, class) == "_p_char"));
  
  
#  assert(length(s_name) >= 64)
  
  ;.Call('R_swig_Neoradio2DeviceInfo_name_set', self, s_name, PACKAGE='neoradio2');
  
}

attr(`Neoradio2DeviceInfo_name_set`, 'returnType') = 'void'
attr(`Neoradio2DeviceInfo_name_set`, "inputTypes") = c('_p__Neoradio2DeviceInfo', '_p_char')
class(`Neoradio2DeviceInfo_name_set`) = c("SWIGFunction", class('Neoradio2DeviceInfo_name_set'))

# Start of Neoradio2DeviceInfo_name_get

`Neoradio2DeviceInfo_name_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;ans = .Call('R_swig_Neoradio2DeviceInfo_name_get', self, as.logical(.copy), PACKAGE='neoradio2');
  ans <- new("_p_char", ref=ans) ;
  
  ans
  
}

attr(`Neoradio2DeviceInfo_name_get`, 'returnType') = '_p_char'
attr(`Neoradio2DeviceInfo_name_get`, "inputTypes") = c('_p__Neoradio2DeviceInfo')
class(`Neoradio2DeviceInfo_name_get`) = c("SWIGFunction", class('Neoradio2DeviceInfo_name_get'))

# Start of Neoradio2DeviceInfo_serial_str_set

`Neoradio2DeviceInfo_serial_str_set` = function(self, s_serial_str)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  
  if(is.list(s_serial_str))
  assert(all(sapply(s_serial_str, class) == "_p_char"));
  
  
#  assert(length(s_serial_str) >= 64)
  
  ;.Call('R_swig_Neoradio2DeviceInfo_serial_str_set', self, s_serial_str, PACKAGE='neoradio2');
  
}

attr(`Neoradio2DeviceInfo_serial_str_set`, 'returnType') = 'void'
attr(`Neoradio2DeviceInfo_serial_str_set`, "inputTypes") = c('_p__Neoradio2DeviceInfo', '_p_char')
class(`Neoradio2DeviceInfo_serial_str_set`) = c("SWIGFunction", class('Neoradio2DeviceInfo_serial_str_set'))

# Start of Neoradio2DeviceInfo_serial_str_get

`Neoradio2DeviceInfo_serial_str_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;ans = .Call('R_swig_Neoradio2DeviceInfo_serial_str_get', self, as.logical(.copy), PACKAGE='neoradio2');
  ans <- new("_p_char", ref=ans) ;
  
  ans
  
}

attr(`Neoradio2DeviceInfo_serial_str_get`, 'returnType') = '_p_char'
attr(`Neoradio2DeviceInfo_serial_str_get`, "inputTypes") = c('_p__Neoradio2DeviceInfo')
class(`Neoradio2DeviceInfo_serial_str_get`) = c("SWIGFunction", class('Neoradio2DeviceInfo_serial_str_get'))

# Start of Neoradio2DeviceInfo_vendor_id_set

`Neoradio2DeviceInfo_vendor_id_set` = function(self, s_vendor_id)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_vendor_id = as.integer(s_vendor_id);
  
  if(length(s_vendor_id) > 1) {
    warning("using only the first element of s_vendor_id");
  };
  
  ;.Call('R_swig_Neoradio2DeviceInfo_vendor_id_set', self, s_vendor_id, PACKAGE='neoradio2');
  
}

attr(`Neoradio2DeviceInfo_vendor_id_set`, 'returnType') = 'void'
attr(`Neoradio2DeviceInfo_vendor_id_set`, "inputTypes") = c('_p__Neoradio2DeviceInfo', 'integer')
class(`Neoradio2DeviceInfo_vendor_id_set`) = c("SWIGFunction", class('Neoradio2DeviceInfo_vendor_id_set'))

# Start of Neoradio2DeviceInfo_vendor_id_get

`Neoradio2DeviceInfo_vendor_id_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_Neoradio2DeviceInfo_vendor_id_get', self, as.logical(.copy), PACKAGE='neoradio2');
  
}

attr(`Neoradio2DeviceInfo_vendor_id_get`, 'returnType') = 'integer'
attr(`Neoradio2DeviceInfo_vendor_id_get`, "inputTypes") = c('_p__Neoradio2DeviceInfo')
class(`Neoradio2DeviceInfo_vendor_id_get`) = c("SWIGFunction", class('Neoradio2DeviceInfo_vendor_id_get'))

# Start of Neoradio2DeviceInfo_product_id_set

`Neoradio2DeviceInfo_product_id_set` = function(self, s_product_id)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_product_id = as.integer(s_product_id);
  
  if(length(s_product_id) > 1) {
    warning("using only the first element of s_product_id");
  };
  
  ;.Call('R_swig_Neoradio2DeviceInfo_product_id_set', self, s_product_id, PACKAGE='neoradio2');
  
}

attr(`Neoradio2DeviceInfo_product_id_set`, 'returnType') = 'void'
attr(`Neoradio2DeviceInfo_product_id_set`, "inputTypes") = c('_p__Neoradio2DeviceInfo', 'integer')
class(`Neoradio2DeviceInfo_product_id_set`) = c("SWIGFunction", class('Neoradio2DeviceInfo_product_id_set'))

# Start of Neoradio2DeviceInfo_product_id_get

`Neoradio2DeviceInfo_product_id_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_Neoradio2DeviceInfo_product_id_get', self, as.logical(.copy), PACKAGE='neoradio2');
  
}

attr(`Neoradio2DeviceInfo_product_id_get`, 'returnType') = 'integer'
attr(`Neoradio2DeviceInfo_product_id_get`, "inputTypes") = c('_p__Neoradio2DeviceInfo')
class(`Neoradio2DeviceInfo_product_id_get`) = c("SWIGFunction", class('Neoradio2DeviceInfo_product_id_get'))

# Start of Neoradio2DeviceInfo__reserved_set

`Neoradio2DeviceInfo__reserved_set` = function(self, s_reserved)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  
  if(is.list(s_reserved))
  assert(all(sapply(s_reserved, class) == "_p_uint8_t"));
  
  
#  assert(length(s_reserved) >= 32)
  
  ;.Call('R_swig_Neoradio2DeviceInfo__reserved_set', self, s_reserved, PACKAGE='neoradio2');
  
}

attr(`Neoradio2DeviceInfo__reserved_set`, 'returnType') = 'void'
attr(`Neoradio2DeviceInfo__reserved_set`, "inputTypes") = c('_p__Neoradio2DeviceInfo', '_p_uint8_t')
class(`Neoradio2DeviceInfo__reserved_set`) = c("SWIGFunction", class('Neoradio2DeviceInfo__reserved_set'))

# Start of Neoradio2DeviceInfo__reserved_get

`Neoradio2DeviceInfo__reserved_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;ans = .Call('R_swig_Neoradio2DeviceInfo__reserved_get', self, as.logical(.copy), PACKAGE='neoradio2');
  ans <- new("_p_uint8_t", ref=ans) ;
  
  ans
  
}

attr(`Neoradio2DeviceInfo__reserved_get`, 'returnType') = '_p_uint8_t'
attr(`Neoradio2DeviceInfo__reserved_get`, "inputTypes") = c('_p__Neoradio2DeviceInfo')
class(`Neoradio2DeviceInfo__reserved_get`) = c("SWIGFunction", class('Neoradio2DeviceInfo__reserved_get'))

# Start of new_Neoradio2DeviceInfo

`Neoradio2DeviceInfo` = function()
{
  ;ans = .Call('R_swig_new_Neoradio2DeviceInfo', PACKAGE='neoradio2');
  ans <- new("_p__Neoradio2DeviceInfo", ref=ans) ;
  
  reg.finalizer(ans@ref, delete_Neoradio2DeviceInfo)
  ans
  
}

attr(`Neoradio2DeviceInfo`, 'returnType') = '_p__Neoradio2DeviceInfo'
class(`Neoradio2DeviceInfo`) = c("SWIGFunction", class('Neoradio2DeviceInfo'))

# Start of delete_Neoradio2DeviceInfo

`delete_Neoradio2DeviceInfo` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_Neoradio2DeviceInfo', self, PACKAGE='neoradio2');
  
}

attr(`delete_Neoradio2DeviceInfo`, 'returnType') = 'void'
attr(`delete_Neoradio2DeviceInfo`, "inputTypes") = c('_p__Neoradio2DeviceInfo')
class(`delete_Neoradio2DeviceInfo`) = c("SWIGFunction", class('delete_Neoradio2DeviceInfo'))

# Start of accessor method for _Neoradio2DeviceInfo
setMethod('$', '_p__Neoradio2DeviceInfo', function(x, name)

{
  accessorFuns = list('name' = Neoradio2DeviceInfo_name_get, 'serial_str' = Neoradio2DeviceInfo_serial_str_get, 'vendor_id' = Neoradio2DeviceInfo_vendor_id_get, 'product_id' = Neoradio2DeviceInfo_product_id_get, '_reserved' = Neoradio2DeviceInfo__reserved_get);
  vaccessors = c('name', 'serial_str', 'vendor_id', 'product_id', '_reserved');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for _Neoradio2DeviceInfo
# Start of accessor method for _Neoradio2DeviceInfo
setMethod('$<-', '_p__Neoradio2DeviceInfo', function(x, name, value)

{
  accessorFuns = list('name' = Neoradio2DeviceInfo_name_set, 'serial_str' = Neoradio2DeviceInfo_serial_str_set, 'vendor_id' = Neoradio2DeviceInfo_vendor_id_set, 'product_id' = Neoradio2DeviceInfo_product_id_set, '_reserved' = Neoradio2DeviceInfo__reserved_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p__Neoradio2DeviceInfo', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('name' = Neoradio2DeviceInfo_name_set, 'serial_str' = Neoradio2DeviceInfo_serial_str_set, 'vendor_id' = Neoradio2DeviceInfo_vendor_id_set, 'product_id' = Neoradio2DeviceInfo_product_id_set, '_reserved' = Neoradio2DeviceInfo__reserved_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for _Neoradio2DeviceInfo
setMethod('delete', '_p__Neoradio2DeviceInfo', function(obj) {delete__Neoradio2DeviceInfo(obj)})
# Start definition of copy functions & methods for Neoradio2DeviceInfo
CopyToR__Neoradio2DeviceInfo = function(value, obj = new("_Neoradio2DeviceInfo"))
{
  obj@name = value$name;
  obj@serial_str = value$serial_str;
  obj@vendor_id = value$vendor_id;
  obj@product_id = value$product_id;
  obj;
}



CopyToC__Neoradio2DeviceInfo = function(value, obj)
{
  obj$name = value@name;
  obj$serial_str = value@serial_str;
  obj$vendor_id = value@vendor_id;
  obj$product_id = value@product_id;
  obj
}



# Start definition of copy methods for Neoradio2DeviceInfo
setMethod('copyToR', '_p_Neoradio2DeviceInfo', CopyToR__Neoradio2DeviceInfo);
setMethod('copyToC', 'Neoradio2DeviceInfo', CopyToC__Neoradio2DeviceInfo);

# End definition of copy methods for Neoradio2DeviceInfo
# End definition of copy functions & methods for Neoradio2DeviceInfo
defineEnumeration('__StatusType',
                    .values = c(
                        'StatusChain' = 0, 
                        'StatusAppStart' = 1, 
                        'StatusPCBSN' = 2, 
                        'StatusSensorRead' = 3, 
                        'StatusSensorWrite' = 4, 
                        'StatusSettingsRead' = 5, 
                        'StatusSettingsWrite' = 6, 
                        'StatusCalibration' = 7, 
                        'StatusCalibrationPoints' = 8, 
                        'StatusCalibrationStored' = 9, 
                        'StatusCalibrationInfo' = 10, 
                        'StatusLedToggle' = 11, 
                        'StatusMax' = 12
))

