/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class CommandStateType {
  public final static CommandStateType CommandStateHost = new CommandStateType("CommandStateHost", neoradio2JNI.CommandStateHost_get());
  public final static CommandStateType CommandStateDevice = new CommandStateType("CommandStateDevice");
  public final static CommandStateType CommandStateUnknown = new CommandStateType("CommandStateUnknown", neoradio2JNI.CommandStateUnknown_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CommandStateType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CommandStateType.class + " with value " + swigValue);
  }

  private CommandStateType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CommandStateType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CommandStateType(String swigName, CommandStateType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CommandStateType[] swigValues = { CommandStateHost, CommandStateDevice, CommandStateUnknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

