/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class StatusType {
  public final static StatusType StatusChain = new StatusType("StatusChain", neoradio2JNI.StatusChain_get());
  public final static StatusType StatusAppStart = new StatusType("StatusAppStart");
  public final static StatusType StatusPCBSN = new StatusType("StatusPCBSN");
  public final static StatusType StatusSensorRead = new StatusType("StatusSensorRead");
  public final static StatusType StatusSensorWrite = new StatusType("StatusSensorWrite");
  public final static StatusType StatusSettingsRead = new StatusType("StatusSettingsRead");
  public final static StatusType StatusSettingsWrite = new StatusType("StatusSettingsWrite");
  public final static StatusType StatusCalibration = new StatusType("StatusCalibration");
  public final static StatusType StatusCalibrationPoints = new StatusType("StatusCalibrationPoints");
  public final static StatusType StatusCalibrationStored = new StatusType("StatusCalibrationStored");
  public final static StatusType StatusCalibrationInfo = new StatusType("StatusCalibrationInfo");
  public final static StatusType StatusLedToggle = new StatusType("StatusLedToggle");
  public final static StatusType StatusMax = new StatusType("StatusMax");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static StatusType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + StatusType.class + " with value " + swigValue);
  }

  private StatusType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private StatusType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private StatusType(String swigName, StatusType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static StatusType[] swigValues = { StatusChain, StatusAppStart, StatusPCBSN, StatusSensorRead, StatusSensorWrite, StatusSettingsRead, StatusSettingsWrite, StatusCalibration, StatusCalibrationPoints, StatusCalibrationStored, StatusCalibrationInfo, StatusLedToggle, StatusMax };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

