/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else



#include "../../../libneoradio2.h"
#include "../../../libneoradio2common.h"

extern void neoradio2_set_blocking(int blocking, long long ms_timeout);
extern int neoradio2_find(Neoradio2DeviceInfo* devices, unsigned int* device_count);
extern int neoradio2_is_blocking();
extern int neoradio2_open(neoradio2_handle* handle, Neoradio2DeviceInfo* device);
extern int neoradio2_is_opened(neoradio2_handle* handle, int* is_opened);
extern int neoradio2_close(neoradio2_handle* handle);
extern int neoradio2_is_closed(neoradio2_handle* handle, int* is_closed);
extern int neoradio2_chain_is_identified(neoradio2_handle* handle, int* is_identified);
extern int neoradio2_chain_identify(neoradio2_handle* handle);
extern int neoradio2_app_is_started(neoradio2_handle* handle, int device, int bank, int* is_started);
extern int neoradio2_app_start(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_enter_bootloader(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_get_serial_number(neoradio2_handle* handle, int device, int bank, unsigned int* serial_number);
extern int neoradio2_get_manufacturer_date(neoradio2_handle* handle, int device, int bank, int* year, int* month, int* day);
extern int neoradio2_get_firmware_version(neoradio2_handle* handle, int device, int bank, int* major, int* minor);
extern int neoradio2_get_hardware_revision(neoradio2_handle* handle, int device, int bank, int* major, int* minor);
extern int neoradio2_get_device_type(neoradio2_handle* handle, int device, int bank, unsigned int* device_type);
extern int neoradio2_request_pcbsn(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_get_pcbsn(neoradio2_handle* handle, int device, int bank, char* pcb_sn);
extern int neoradio2_request_sensor_data(neoradio2_handle* handle, int device, int bank, int enable_cal);
extern int neoradio2_read_sensor_float(neoradio2_handle* handle, int device, int bank, float* value);
extern int neoradio2_read_sensor_array(neoradio2_handle* handle, int device, int bank, int* arr, int* arr_size);
extern int neoradio2_write_sensor(neoradio2_handle* handle, int device, int bank, int mask, int value);
extern int neoradio2_write_sensor_successful(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_request_settings(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_read_settings(neoradio2_handle* handle, int device, int bank, neoRADIO2_settings* settings);
extern int neoradio2_write_settings(neoradio2_handle* handle, int device, int bank, neoRADIO2_settings* settings);
extern int neoradio2_write_settings_successful(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_get_chain_count(neoradio2_handle* handle, int* count, int identify);
extern int neoradio2_request_calibration(neoradio2_handle* handle, int device, int bank, neoRADIO2frame_calHeader* header);
extern int neoradio2_read_calibration_array(neoradio2_handle* handle, int device, int bank, neoRADIO2frame_calHeader* header, float* arr, int* arr_size);
extern int neoradio2_request_calibration_points(neoradio2_handle* handle, int device, int bank, neoRADIO2frame_calHeader* header);
extern int neoradio2_read_calibration_points_array(neoradio2_handle* handle, int device, int bank, neoRADIO2frame_calHeader* header, float* arr, int* arr_size);
extern int neoradio2_write_calibration(neoradio2_handle* handle, int device, int bank, neoRADIO2frame_calHeader* header, float* arr, int arr_size);
extern int neoradio2_write_calibration_successful(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_write_calibration_points(neoradio2_handle* handle, int device, int bank, neoRADIO2frame_calHeader* header, float* arr, int arr_size);
extern int neoradio2_write_calibration_points_successful(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_store_calibration(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_is_calibration_stored(neoradio2_handle* handle, int device, int bank, int* stored);
extern int neoradio2_get_calibration_is_valid(neoradio2_handle* handle, int device, int bank, int* is_valid);

extern int neoradio2_request_calibration_info(neoradio2_handle* handle, int device, int bank);
extern int neoradio2_read_calibration_info(neoradio2_handle* handle, int device, int bank, neoRADIO2frame_calHeader* header);


extern int neoradio2_toggle_led(neoradio2_handle* handle, int device, int bank, int ms);
extern int neoradio2_toggle_led_successful(neoradio2_handle* handle, int device, int bank);


extern int neoradio2_get_status(neoradio2_handle* handle, int device, int bank, int bitfield, StatusType type, CommandStatus* status);



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_neoradio2JNI_StatusInProgress_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  _CommandStatus result;
  
  (void)jenv;
  (void)jcls;
  result = (_CommandStatus)StatusInProgress;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_CommandStateHost_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  _CommandStateType result;
  
  (void)jenv;
  (void)jcls;
  result = (_CommandStateType)CommandStateHost;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_CommandStateUnknown_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  _CommandStateType result;
  
  (void)jenv;
  (void)jcls;
  result = (_CommandStateType)CommandStateUnknown;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_NEORADIO2_1SUCCESS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_NEORADIO2_1FAILURE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_NEORADIO2_1ERR_1WBLOCK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_NEORADIO2_1ERR_1INPROGRESS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_NEORADIO2_1ERR_1FAILURE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_NEORADIO2_1MAX_1DEVS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  char *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->name, (const char *)arg2, 64-1);
      arg1->name[64-1] = 0;
    } else {
      arg1->name[0] = 0;
    }
  }
  
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  result = (char *)(char *) ((arg1)->name);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1serial_1str_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  char *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  {
    if(arg2) {
      strncpy((char*)arg1->serial_str, (const char *)arg2, 64-1);
      arg1->serial_str[64-1] = 0;
    } else {
      arg1->serial_str[0] = 0;
    }
  }
  
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1serial_1str_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  result = (char *)(char *) ((arg1)->serial_str);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1vendor_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->vendor_id = arg2;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1vendor_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  result = (int) ((arg1)->vendor_id);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1product_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->product_id = arg2;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1product_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  result = (int) ((arg1)->product_id);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1_1reserved_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  uint8_t *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  {
    size_t ii;
    uint8_t *b = (uint8_t *) arg1->_reserved;
    for (ii = 0; ii < (size_t)32; ii++) b[ii] = *((uint8_t *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_neoradio2JNI_Neoradio2DeviceInfo_1_1reserved_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  uint8_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  result = (uint8_t *)(uint8_t *) ((arg1)->_reserved);
  *(uint8_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_neoradio2JNI_new_1Neoradio2DeviceInfo(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  _Neoradio2DeviceInfo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (_Neoradio2DeviceInfo *)new _Neoradio2DeviceInfo();
  *(_Neoradio2DeviceInfo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_neoradio2JNI_delete_1Neoradio2DeviceInfo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _Neoradio2DeviceInfo *arg1 = (_Neoradio2DeviceInfo *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_Neoradio2DeviceInfo **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jint JNICALL Java_neoradio2JNI_StatusChain_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  _StatusType result;
  
  (void)jenv;
  (void)jcls;
  result = (_StatusType)StatusChain;
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

